### ISSUE TITLE
Unable to download the pointrend weights

### ISSUE THREAD

**Issue by brjathu** [jasonyzhang/data#1]
Hi,

I am trying to download the pointrend weights, but it seems the file is not fully uploaded.

**Comment by jasonyzhang** [comment]
Hi,

It appears that there's a quota for the  total bandwidth of downloads for Git-LFS. I've uploaded the weights to google drive here: https://drive.google.com/file/d/1SoFg6AjB17CIekGvAf_sLIuCE7wEmVfK/view?usp=sharing

Best,
Jason
